//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 08/10/2020 10:23:51
namespace AlumnosService.entities
{
    /// <summary>
    /// There are no comments for CentroSingle in the schema.
    /// </summary>
    public partial class CentroSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Centro>
    {
        /// <summary>
        /// Initialize a new CentroSingle object.
        /// </summary>
        public CentroSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CentroSingle object.
        /// </summary>
        public CentroSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CentroSingle object.
        /// </summary>
        public CentroSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Centro> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Alumnos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Alumno> Alumnos
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Alumnos == null))
                {
                    this._Alumnos = Context.CreateQuery<global::AlumnosService.entities.Alumno>(GetPath("Alumnos"));
                }
                return this._Alumnos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Alumno> _Alumnos;
    }
    /// <summary>
    /// There are no comments for Centro in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Centro : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Centro object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Centro CreateCentro(global::System.Guid ID)
        {
            Centro centro = new Centro();
            centro.Id = ID;
            return centro;
        }
        /// <summary>
        /// There are no comments for Property Nombre in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this._Nombre = value;
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Nombre;
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Alumnos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.Alumno> Alumnos
        {
            get
            {
                return this._Alumnos;
            }
            set
            {
                this.OnAlumnosChanging(value);
                this._Alumnos = value;
                this.OnAlumnosChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.Alumno> _Alumnos = new global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.Alumno>();
        partial void OnAlumnosChanging(global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.Alumno> value);
        partial void OnAlumnosChanged();
    }
    /// <summary>
    /// There are no comments for AsignaturaSingle in the schema.
    /// </summary>
    public partial class AsignaturaSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Asignatura>
    {
        /// <summary>
        /// Initialize a new AsignaturaSingle object.
        /// </summary>
        public AsignaturaSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AsignaturaSingle object.
        /// </summary>
        public AsignaturaSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AsignaturaSingle object.
        /// </summary>
        public AsignaturaSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Asignatura> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for AlumnosAsignatura in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.AlumnoAsignatura> AlumnosAsignatura
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._AlumnosAsignatura == null))
                {
                    this._AlumnosAsignatura = Context.CreateQuery<global::AlumnosService.entities.AlumnoAsignatura>(GetPath("AlumnosAsignatura"));
                }
                return this._AlumnosAsignatura;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.AlumnoAsignatura> _AlumnosAsignatura;
    }
    /// <summary>
    /// There are no comments for Asignatura in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Asignatura : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Asignatura object.
        /// </summary>
        /// <param name="creditos">Initial value of Creditos.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Asignatura CreateAsignatura(int creditos, global::System.Guid ID)
        {
            Asignatura asignatura = new Asignatura();
            asignatura.Creditos = creditos;
            asignatura.Id = ID;
            return asignatura;
        }
        /// <summary>
        /// There are no comments for Property Nombre in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this._Nombre = value;
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Nombre;
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        /// <summary>
        /// There are no comments for Property Creditos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual int Creditos
        {
            get
            {
                return this._Creditos;
            }
            set
            {
                this.OnCreditosChanging(value);
                this._Creditos = value;
                this.OnCreditosChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Creditos;
        partial void OnCreditosChanging(int value);
        partial void OnCreditosChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property AlumnosAsignatura in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.AlumnoAsignatura> AlumnosAsignatura
        {
            get
            {
                return this._AlumnosAsignatura;
            }
            set
            {
                this.OnAlumnosAsignaturaChanging(value);
                this._AlumnosAsignatura = value;
                this.OnAlumnosAsignaturaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.AlumnoAsignatura> _AlumnosAsignatura = new global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.AlumnoAsignatura>();
        partial void OnAlumnosAsignaturaChanging(global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.AlumnoAsignatura> value);
        partial void OnAlumnosAsignaturaChanged();
    }
    /// <summary>
    /// There are no comments for AlumnoSingle in the schema.
    /// </summary>
    public partial class AlumnoSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Alumno>
    {
        /// <summary>
        /// Initialize a new AlumnoSingle object.
        /// </summary>
        public AlumnoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AlumnoSingle object.
        /// </summary>
        public AlumnoSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AlumnoSingle object.
        /// </summary>
        public AlumnoSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Alumno> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Centro in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::AlumnosService.entities.CentroSingle Centro
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Centro == null))
                {
                    this._Centro = new global::AlumnosService.entities.CentroSingle(this.Context, GetPath("Centro"));
                }
                return this._Centro;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::AlumnosService.entities.CentroSingle _Centro;
        /// <summary>
        /// There are no comments for AlumnoAsignaturas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.AlumnoAsignatura> AlumnoAsignaturas
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._AlumnoAsignaturas == null))
                {
                    this._AlumnoAsignaturas = Context.CreateQuery<global::AlumnosService.entities.AlumnoAsignatura>(GetPath("AlumnoAsignaturas"));
                }
                return this._AlumnoAsignaturas;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.AlumnoAsignatura> _AlumnoAsignaturas;
    }
    /// <summary>
    /// There are no comments for Alumno in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class Alumno : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new Alumno object.
        /// </summary>
        /// <param name="fechaNacimiento">Initial value of FechaNacimiento.</param>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static Alumno CreateAlumno(global::System.DateTimeOffset fechaNacimiento, global::System.Guid ID)
        {
            Alumno alumno = new Alumno();
            alumno.FechaNacimiento = fechaNacimiento;
            alumno.Id = ID;
            return alumno;
        }
        /// <summary>
        /// There are no comments for Property Nombre in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this._Nombre = value;
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Nombre;
        partial void OnNombreChanging(string value);
        partial void OnNombreChanged();
        /// <summary>
        /// There are no comments for Property Apellido1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Apellido1
        {
            get
            {
                return this._Apellido1;
            }
            set
            {
                this.OnApellido1Changing(value);
                this._Apellido1 = value;
                this.OnApellido1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Apellido1;
        partial void OnApellido1Changing(string value);
        partial void OnApellido1Changed();
        /// <summary>
        /// There are no comments for Property Apellido2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual string Apellido2
        {
            get
            {
                return this._Apellido2;
            }
            set
            {
                this.OnApellido2Changing(value);
                this._Apellido2 = value;
                this.OnApellido2Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Apellido2;
        partial void OnApellido2Changing(string value);
        partial void OnApellido2Changed();
        /// <summary>
        /// There are no comments for Property FechaNacimiento in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.DateTimeOffset FechaNacimiento
        {
            get
            {
                return this._FechaNacimiento;
            }
            set
            {
                this.OnFechaNacimientoChanging(value);
                this._FechaNacimiento = value;
                this.OnFechaNacimientoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _FechaNacimiento;
        partial void OnFechaNacimientoChanging(global::System.DateTimeOffset value);
        partial void OnFechaNacimientoChanged();
        /// <summary>
        /// There are no comments for Property FechaBaja in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> FechaBaja
        {
            get
            {
                return this._FechaBaja;
            }
            set
            {
                this.OnFechaBajaChanging(value);
                this._FechaBaja = value;
                this.OnFechaBajaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _FechaBaja;
        partial void OnFechaBajaChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnFechaBajaChanged();
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Centro in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::AlumnosService.entities.Centro Centro
        {
            get
            {
                return this._Centro;
            }
            set
            {
                this.OnCentroChanging(value);
                this._Centro = value;
                this.OnCentroChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::AlumnosService.entities.Centro _Centro;
        partial void OnCentroChanging(global::AlumnosService.entities.Centro value);
        partial void OnCentroChanged();
        /// <summary>
        /// There are no comments for Property AlumnoAsignaturas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.AlumnoAsignatura> AlumnoAsignaturas
        {
            get
            {
                return this._AlumnoAsignaturas;
            }
            set
            {
                this.OnAlumnoAsignaturasChanging(value);
                this._AlumnoAsignaturas = value;
                this.OnAlumnoAsignaturasChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.AlumnoAsignatura> _AlumnoAsignaturas = new global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.AlumnoAsignatura>();
        partial void OnAlumnoAsignaturasChanging(global::System.Collections.ObjectModel.Collection<global::AlumnosService.entities.AlumnoAsignatura> value);
        partial void OnAlumnoAsignaturasChanged();
    }
    /// <summary>
    /// There are no comments for AlumnoAsignaturaSingle in the schema.
    /// </summary>
    public partial class AlumnoAsignaturaSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<AlumnoAsignatura>
    {
        /// <summary>
        /// Initialize a new AlumnoAsignaturaSingle object.
        /// </summary>
        public AlumnoAsignaturaSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new AlumnoAsignaturaSingle object.
        /// </summary>
        public AlumnoAsignaturaSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new AlumnoAsignaturaSingle object.
        /// </summary>
        public AlumnoAsignaturaSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<AlumnoAsignatura> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Alumno in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::AlumnosService.entities.AlumnoSingle Alumno
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Alumno == null))
                {
                    this._Alumno = new global::AlumnosService.entities.AlumnoSingle(this.Context, GetPath("Alumno"));
                }
                return this._Alumno;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::AlumnosService.entities.AlumnoSingle _Alumno;
        /// <summary>
        /// There are no comments for Asignatura in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::AlumnosService.entities.AsignaturaSingle Asignatura
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Asignatura == null))
                {
                    this._Asignatura = new global::AlumnosService.entities.AsignaturaSingle(this.Context, GetPath("Asignatura"));
                }
                return this._Asignatura;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::AlumnosService.entities.AsignaturaSingle _Asignatura;
    }
    /// <summary>
    /// There are no comments for AlumnoAsignatura in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    public partial class AlumnoAsignatura : global::Microsoft.OData.Client.BaseEntityType
    {
        /// <summary>
        /// Create a new AlumnoAsignatura object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static AlumnoAsignatura CreateAlumnoAsignatura(global::System.Guid ID)
        {
            AlumnoAsignatura alumnoAsignatura = new AlumnoAsignatura();
            alumnoAsignatura.Id = ID;
            return alumnoAsignatura;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Alumno in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::AlumnosService.entities.Alumno Alumno
        {
            get
            {
                return this._Alumno;
            }
            set
            {
                this.OnAlumnoChanging(value);
                this._Alumno = value;
                this.OnAlumnoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::AlumnosService.entities.Alumno _Alumno;
        partial void OnAlumnoChanging(global::AlumnosService.entities.Alumno value);
        partial void OnAlumnoChanged();
        /// <summary>
        /// There are no comments for Property Asignatura in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::AlumnosService.entities.Asignatura Asignatura
        {
            get
            {
                return this._Asignatura;
            }
            set
            {
                this.OnAsignaturaChanging(value);
                this._Asignatura = value;
                this.OnAsignaturaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::AlumnosService.entities.Asignatura _Asignatura;
        partial void OnAsignaturaChanging(global::AlumnosService.entities.Asignatura value);
        partial void OnAsignaturaChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::AlumnosService.entities.Centro as global::AlumnosService.entities.CentroSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AlumnosService.entities.CentroSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Centro> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::AlumnosService.entities.CentroSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AlumnosService.entities.Centro as global::AlumnosService.entities.CentroSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::AlumnosService.entities.CentroSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Centro> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::AlumnosService.entities.CentroSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AlumnosService.entities.Asignatura as global::AlumnosService.entities.AsignaturaSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AlumnosService.entities.AsignaturaSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Asignatura> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::AlumnosService.entities.AsignaturaSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AlumnosService.entities.Asignatura as global::AlumnosService.entities.AsignaturaSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::AlumnosService.entities.AsignaturaSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Asignatura> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::AlumnosService.entities.AsignaturaSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AlumnosService.entities.Alumno as global::AlumnosService.entities.AlumnoSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AlumnosService.entities.AlumnoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Alumno> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::AlumnosService.entities.AlumnoSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AlumnosService.entities.Alumno as global::AlumnosService.entities.AlumnoSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::AlumnosService.entities.AlumnoSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Alumno> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::AlumnosService.entities.AlumnoSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AlumnosService.entities.AlumnoAsignatura as global::AlumnosService.entities.AlumnoAsignaturaSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::AlumnosService.entities.AlumnoAsignaturaSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.AlumnoAsignatura> source, global::System.Collections.Generic.IDictionary<string, object> keys)
        {
            return new global::AlumnosService.entities.AlumnoAsignaturaSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::AlumnosService.entities.AlumnoAsignatura as global::AlumnosService.entities.AlumnoAsignaturaSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::AlumnosService.entities.AlumnoAsignaturaSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.AlumnoAsignatura> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.IDictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::AlumnosService.entities.AlumnoAsignaturaSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace AlumnosService.Microsoft.AspNetCore.Mvc
{
}
namespace AlumnosService.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Microsoft.AspNetCore.Mvc", "AlumnosService.Microsoft.AspNetCore.Mvc");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "entities", "AlumnosService.entities");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "AlumnosService.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("AlumnosService.Microsoft.AspNetCore.Mvc", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Microsoft.AspNetCore.Mvc.", clientType.Name);
            }
            if (clientType.Namespace.Equals("AlumnosService.entities", global::System.StringComparison.Ordinal))
            {
                return string.Concat("entities.", clientType.Name);
            }
            if (clientType.Namespace.Equals("AlumnosService.Default", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Centros in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Centro> Centros
        {
            get
            {
                if ((this._Centros == null))
                {
                    this._Centros = base.CreateQuery<global::AlumnosService.entities.Centro>("Centros");
                }
                return this._Centros;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Centro> _Centros;
        /// <summary>
        /// There are no comments for Asignaturas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Asignatura> Asignaturas
        {
            get
            {
                if ((this._Asignaturas == null))
                {
                    this._Asignaturas = base.CreateQuery<global::AlumnosService.entities.Asignatura>("Asignaturas");
                }
                return this._Asignaturas;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Asignatura> _Asignaturas;
        /// <summary>
        /// There are no comments for Alumnos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Alumno> Alumnos
        {
            get
            {
                if ((this._Alumnos == null))
                {
                    this._Alumnos = base.CreateQuery<global::AlumnosService.entities.Alumno>("Alumnos");
                }
                return this._Alumnos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::AlumnosService.entities.Alumno> _Alumnos;
        /// <summary>
        /// There are no comments for Centros in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToCentros(global::AlumnosService.entities.Centro centro)
        {
            base.AddObject("Centros", centro);
        }
        /// <summary>
        /// There are no comments for Asignaturas in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToAsignaturas(global::AlumnosService.entities.Asignatura asignatura)
        {
            base.AddObject("Asignaturas", asignatura);
        }
        /// <summary>
        /// There are no comments for Alumnos in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToAlumnos(global::AlumnosService.entities.Alumno alumno)
        {
            base.AddObject("Alumnos", alumno);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"AlumnosServiceCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, false, out edmModel, out errors))
                    {
	                    global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
	                    foreach (var error in errors)
	                    {
		                    errorMessages.Append(error.ErrorMessage);
		                    errorMessages.Append("; ");
	                    }
	                    throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
